services:

  tailscale:
    image: tailscale/tailscale:stable
    # "hostname" appears as the device name in the Tailscale network.
    # For example, "my-service.my-tailscale-network.ts.net".
    # This domain name is used in "Caddyfile".
    hostname: my-service
    environment:
      # Tailscale OAuth secret.
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=${TS_EXTRA_ARGS}
      # Tailscale state dir
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      # See "volumes:" below for details.
      - ts-lib-var:/var/lib/tailscale
      - ts-run-var:/var/run/tailscale
      - ts-tmp:/tmp
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ts-run-var:/var/run/tailscale
      - ts-tmp:/tmp
    depends_on:
      - tailscale
    network_mode: service:tailscale

  # A service behind Tailscale and Caddy reverse proxy.
  # In this case, nginx serving a static html at port 8080.
  # The name "web" is used in "Caddyfile".
  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./templates:/etc/nginx/templates
      - ./html:/usr/share/nginx/html:ro
    # Expose port to Caddy.
    expose:
      - 8585
    environment:
      # "default.conf.template" uses this variable.
      - PORT=8585
    depends_on:
      - tailscale
      - caddy


volumes:
  # Tailscale state dir.
  ts-lib-var:
    driver: local
  # For "/var/run/tailscale/tailscaled.sock".
  # Shared between tailscale and caddy containers.
  ts-run-var:
    driver: local
  # For "/tmp/tailscaled.sock" because "/var/run/tailscale/tailscaled.sock" is symlinked to it.
  # Shared between tailscale and caddy containers.
  ts-tmp:
    driver: local
